spring.application.name=savi-project


spring.datasource.url=jdbc:postgresql://localhost:5433/aryan
spring.datasource.username=savi
spring.datasource.password=vishu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true



